import Footer from './components/layout/Footer';
import Header from './components/layout/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

import { createClient } from 'contentful';

const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_CONTENT_DELIVERY,
});

export const metadata = {
  title: 'YouTube Explained – Julian Hicks',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const footer = await client.getEntry('554j8fBbiwATrMGIvwZOSJ');
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer props={footer} />
      </body>
    </html>
  );
}
